kind: pipeline
name: default

steps:

  - name: Test
    image: openjdk:11-jdk
    commands:
      - ./gradlew build test jacocoTestReport

  - name: Coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
      files:
        - build/reports/jacoco/report.xml

  - name: Installers
    image: openjdk:11-jdk
    commands:
      - wget https://download-keycdn.ej-technologies.com/install4j/install4j_linux_7_0_9.deb
      - dpkg -i install4j_linux_7_0_9.deb
      - ./gradlew install4j
    environment:
      i4jlicense:
        from_secret: install4jkey
    when:
      event:
        - tag